rails_tutorial_url: "http://www.railstutorial.org/"
rails_tutorial_book_url: "http://www.railstutorial.org/book"
rails_tutorial_help_url: "http://www.railstutorial.org/help"

user:
  max_name_length: 50
  max_email_length: 255
  birthday_year_limit: 100
